default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db_user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_pass] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: onebitflix_development

test:
  <<: *default
  database: onebitflix_test

production:
  <<: *default
  database: onebitflix_production
  username: onebitflix
  password: <%= ENV['ONEBITFLIX_DATABASE_PASSWORD'] %>
